--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.225.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2025.06.02 10:47:33
-- Server version: 10.4.32
--

SET NAMES 'utf8';

INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(1, 'Mystical Red Flower', 'Mystical Red Seed', 'Mana', NULL, 'Flower Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(2, 'Mystical Blue Flower', 'Mystical Blue Seed', 'Mana', NULL, 'Flower Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(3, 'Mystical Yellow Flower', 'Mystical Yellow Seed', 'Mana', NULL, 'Flower Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(4, 'Mystical Green Flower', 'Mystical Green Seed', 'Mana', NULL, 'Flower Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(5, 'Mystical White Flower', 'Mystical White Seed', 'Mana', NULL, 'Flower Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(6, 'Mystical Purple Flower', 'Mystical Purple Seed', 'Mana', NULL, 'Flower Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(7, 'Mystical Black Flower', 'Mystical Black Seed', 'Mana', NULL, 'Flower Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(8, 'Mystical Pink Flower', 'Mystical Pink Seed', 'Mana', NULL, 'Flower Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(9, 'Mystical Orange Flower', 'Mystical Orange Seed', 'Mana', NULL, 'Flower Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(10, 'Mystical Lime Flower', 'Mystical Lime Seed', 'Mana', NULL, 'Flower Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(11, 'Mystical Brown Flower', 'Mystical Brown Seed', 'Mana', NULL, 'Flower Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(12, 'Mystical Violet Flower', 'Mystical Violet Seed', 'Mana', NULL, 'Flower Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(13, 'Mystical Light Blue Flower', 'Mystical Light Blue Seed', 'Mana', NULL, 'Flower Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(14, 'Mystical Magenta Flower', 'Mystical Magenta Seed', 'Mana', NULL, 'Flower Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(15, 'Red Petal', 'Mystical Red Flower', 'Mana', NULL, 'Petal Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(16, 'Blue Petal', 'Mystical Blue Flower', 'Mana', NULL, 'Petal Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(17, 'Yellow Petal', 'Mystical Yellow Flower', 'Mana', NULL, 'Petal Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(18, 'Green Petal', 'Mystical Green Flower', 'Mana', NULL, 'Petal Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(19, 'White Petal', 'Mystical White Flower', 'Mana', NULL, 'Petal Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(20, 'Purple Petal', 'Mystical Purple Flower', 'Mana', NULL, 'Petal Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(21, 'Black Petal', 'Mystical Black Flower', 'Mana', NULL, 'Petal Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(22, 'Pink Petal', 'Mystical Pink Flower', 'Mana', NULL, 'Petal Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(23, 'Orange Petal', 'Mystical Orange Flower', 'Mana', NULL, 'Petal Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(24, 'Lime Petal', 'Mystical Lime Flower', 'Mana', NULL, 'Petal Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(25, 'Brown Petal', 'Mystical Brown Flower', 'Mana', NULL, 'Petal Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(26, 'Violet Petal', 'Mystical Violet Flower', 'Mana', NULL, 'Petal Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(27, 'Light Blue Petal', 'Mystical Light Blue Flower', 'Mana', NULL, 'Petal Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(28, 'Magenta Petal', 'Mystical Magenta Flower', 'Mana', NULL, 'Petal Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(29, 'Mystical Red Seed', 'Mystical Red Flower', 'Mana', NULL, 'Seed Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(30, 'Mystical Blue Seed', 'Mystical Blue Flower', 'Mana', NULL, 'Seed Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(31, 'Mystical Yellow Seed', 'Mystical Yellow Flower', 'Mana', NULL, 'Seed Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(32, 'Mystical Green Seed', 'Mystical Green Flower', 'Mana', NULL, 'Seed Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(33, 'Mystical White Seed', 'Mystical White Flower', 'Mana', NULL, 'Seed Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(34, 'Mystical Purple Seed', 'Mystical Purple Flower', 'Mana', NULL, 'Seed Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(35, 'Mystical Black Seed', 'Mystical Black Flower', 'Mana', NULL, 'Seed Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(36, 'Mystical Pink Seed', 'Mystical Pink Flower', 'Mana', NULL, 'Seed Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(37, 'Mystical Orange Seed', 'Mystical Orange Flower', 'Mana', NULL, 'Seed Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(38, 'Mystical Lime Seed', 'Mystical Lime Flower', 'Mana', NULL, 'Seed Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(39, 'Mystical Brown Seed', 'Mystical Brown Flower', 'Mana', NULL, 'Seed Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(40, 'Mystical Violet Seed', 'Mystical Violet Flower', 'Mana', NULL, 'Seed Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(41, 'Mystical Light Blue Seed', 'Mystical Light Blue Flower', 'Mana', NULL, 'Seed Crafting', 1);
INSERT INTO botania.craftingrecipes(RecipeID, Result, Ingredient1, Ingredient2, Ingredient3, CraftingType, Amount) VALUES
(42, 'Mystical Magenta Seed', 'Mystical Magenta Flower', 'Mana', NULL, 'Seed Crafting', 1);