--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.225.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2025.06.02 10:47:33
-- Server version: 10.4.32
--

SET NAMES 'utf8';

INSERT INTO botania.flowers(FlowerID, Name, Type, ManaUsage, Abilities, CraftingRecipe, WorldGenType, Biome, SpawnRate, IsRare) VALUES
(1, 'Mystical Red Flower', 'WorldGen', 0, 'Used in crafting for Botania recipes', 'Mystical Red Petal', 'Biome-based', 'Plains', 10.00, 0);
INSERT INTO botania.flowers(FlowerID, Name, Type, ManaUsage, Abilities, CraftingRecipe, WorldGenType, Biome, SpawnRate, IsRare) VALUES
(2, 'Mystical Blue Flower', 'WorldGen', 0, 'Used in crafting for Botania recipes', 'Mystical Blue Petal', 'Biome-based', 'Forest', 8.00, 0);
INSERT INTO botania.flowers(FlowerID, Name, Type, ManaUsage, Abilities, CraftingRecipe, WorldGenType, Biome, SpawnRate, IsRare) VALUES
(3, 'Mystical Yellow Flower', 'WorldGen', 0, 'Used in crafting for Botania recipes', 'Mystical Yellow Petal', 'Biome-based', 'Plains', 12.00, 0);
INSERT INTO botania.flowers(FlowerID, Name, Type, ManaUsage, Abilities, CraftingRecipe, WorldGenType, Biome, SpawnRate, IsRare) VALUES
(4, 'Mystical Green Flower', 'WorldGen', 0, 'Used in crafting for Botania recipes', 'Mystical Green Petal', 'Biome-based', 'Swamp', 5.00, 0);
INSERT INTO botania.flowers(FlowerID, Name, Type, ManaUsage, Abilities, CraftingRecipe, WorldGenType, Biome, SpawnRate, IsRare) VALUES
(5, 'Mystical White Flower', 'WorldGen', 0, 'Used in crafting for Botania recipes', 'Mystical White Petal', 'Biome-based', 'Forest', 6.00, 0);
INSERT INTO botania.flowers(FlowerID, Name, Type, ManaUsage, Abilities, CraftingRecipe, WorldGenType, Biome, SpawnRate, IsRare) VALUES
(6, 'Mystical Purple Flower', 'WorldGen', 0, 'Used in crafting for Botania recipes', 'Mystical Purple Petal', 'Biome-based', 'Mountain', 4.00, 0);
INSERT INTO botania.flowers(FlowerID, Name, Type, ManaUsage, Abilities, CraftingRecipe, WorldGenType, Biome, SpawnRate, IsRare) VALUES
(7, 'Mystical Black Flower', 'WorldGen', 0, 'Used in crafting for Botania recipes', 'Mystical Black Petal', 'Biome-based', 'Jungle', 3.00, 1);
INSERT INTO botania.flowers(FlowerID, Name, Type, ManaUsage, Abilities, CraftingRecipe, WorldGenType, Biome, SpawnRate, IsRare) VALUES
(8, 'Mystical Pink Flower', 'WorldGen', 0, 'Used in crafting for Botania recipes', 'Mystical Pink Petal', 'Biome-based', 'Flower Forest', 2.50, 1);