--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.225.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2025.06.02 10:49:00
-- Server version: 10.4.32
--

SET NAMES 'utf8';

INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(1, 'Crafty Crate', 'Crafting', 'A crate that can automatically craft items from its inventory using mana.', 'Wood + Mana Pool + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(2, 'Open Crate', 'Crafting', 'A crate that automatically opens and outputs items from its inventory using mana.', 'Wood + Mana Pool + Petals', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(3, 'Force Relay', 'Mana Transport', 'A device that sends mana to nearby devices using force beams and stores mana.', 'Mana Pool + Livingwood + Force Crystal', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(4, 'Drum of the Wild', 'World Interaction', 'A drum that modifies the environment by growing trees and plants when played.', 'Drum + Mana + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(5, 'Drum of the Gathering', 'World Interaction', 'A drum that collects items within a certain radius when played.', 'Drum + Mana + Gathering Sigil', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(6, 'Drum of the Canopy', 'World Interaction', 'A drum that increases the growth speed of nearby trees when played.', 'Drum + Mana + Canopy Sigil', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(7, 'Livingwood Avatar', 'World Interaction', 'A block that creates an avatar made of livingwood to perform actions when activated.', 'Livingwood + Mana + Avatar Sigil', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(8, 'Mana Pool', 'Mana Generation', 'The basic pool that stores mana from various sources like mana-generating flowers.', 'Livingwood + Mana Pool + Petals', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(9, 'Diluted Mana Pool', 'Mana Generation', 'A weaker variant of the Mana Pool that stores less mana.', 'Livingwood + Mana Pool + Petals + Dye', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(10, 'Fabulous Mana Pool', 'Mana Generation', 'An upgraded Mana Pool that stores more mana and has enhanced properties.', 'Livingwood + Mana Pool + Precious Stones', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(11, 'The Everlasting Guilty Pool', 'Mana Generation', 'A special Mana Pool with infinite mana storage capacity.', 'Livingwood + Mana Pool + Rare Gems', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(12, 'Mana Spreader', 'Mana Transport', 'Transports mana from a Mana Pool or Mana Generator to other blocks.', 'Livingwood + Mana Spreader', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(13, 'Pulse Mana Spreader', 'Mana Transport', 'A specialized Mana Spreader that pulses mana at intervals.', 'Livingwood + Pulse Mana Spreader + Mana Pool', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(14, 'Elven Mana Spreader', 'Mana Transport', 'An Elven variant of the Mana Spreader that uses enhanced mana transfer capabilities.', 'Livingwood + Elven Mana Spreader + Mana Pool', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(15, 'Gaia Mana Spreader', 'Mana Transport', 'A powerful Mana Spreader that requires mana from Gaia-related sources.', 'Livingwood + Gaia Mana Spreader + Mana Pool', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(16, 'Bore Bore', 'Mana Manipulation', 'A Mana Lens that focuses mana to bore through blocks in the world.', 'Mana Lens + Bore + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(17, 'Bounce Bounce', 'Mana Manipulation', 'A Mana Lens that causes mana to bounce off surfaces and continue in a different direction.', 'Mana Lens + Bounce + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(18, 'Celebratory Celebratory', 'Mana Manipulation', 'A Mana Lens that causes mana to explode into a burst of celebratory effects when activated.', 'Mana Lens + Celebratory + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(19, 'Damaging Damaging', 'Mana Manipulation', 'A Mana Lens that causes the mana to deal damage to nearby entities.', 'Mana Lens + Damaging + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(20, 'Efficiency Efficiency', 'Mana Manipulation', 'A Mana Lens that increases the efficiency of mana transfer to nearby blocks.', 'Mana Lens + Efficiency + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(21, 'Entropic Entropic', 'Mana Manipulation', 'A Mana Lens that causes entropy and disturbs the mana flow, destabilizing areas around it.', 'Mana Lens + Entropic + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(22, 'Flare Flare', 'Mana Manipulation', 'A Mana Lens that shoots out mana in a flare-like burst of light and energy.', 'Mana Lens + Flare + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(23, 'Flash Flash', 'Mana Manipulation', 'A Mana Lens that causes mana to release as a brief flash of intense energy.', 'Mana Lens + Flash + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(24, 'Force Force', 'Mana Manipulation', 'A Mana Lens that channels mana with a forceful push to move objects and push back entities.', 'Mana Lens + Force + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(25, 'Gravity Gravity', 'Mana Manipulation', 'A Mana Lens that manipulates gravity, causing entities to move in different directions based on mana flow.', 'Mana Lens + Gravity + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(26, 'Kindle Kindle', 'Mana Manipulation', 'A Mana Lens that can ignite objects or entities by channeling mana.', 'Mana Lens + Kindle + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(27, 'Influence Influence', 'Mana Manipulation', 'A Mana Lens that controls and influences nearby entities, altering their behavior.', 'Mana Lens + Influence + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(28, 'Magnetizing Magnetizing', 'Mana Manipulation', 'A Mana Lens that magnetizes nearby items or entities to pull them towards it.', 'Mana Lens + Magnetizing + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(29, 'Messenger Messenger', 'Mana Manipulation', 'A Mana Lens that sends messages or signals through the mana beams.', 'Mana Lens + Messenger + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(30, 'Paintslinger Paintslinger', 'Mana Manipulation', 'A Mana Lens that can paint or change the color of blocks or entities within its range.', 'Mana Lens + Paintslinger + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(31, 'Phantom Phantom', 'Mana Manipulation', 'A Mana Lens that generates phantom images or duplicates of blocks in its range.', 'Mana Lens + Phantom + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(32, 'Potency Potency', 'Mana Manipulation', 'A Mana Lens that increases the potency and power of nearby mana interactions.', 'Mana Lens + Potency + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(33, 'Redirective Redirective', 'Mana Manipulation', 'A Mana Lens that can redirect mana beams to different locations.', 'Mana Lens + Redirective + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(34, 'Resistance Resistance', 'Mana Manipulation', 'A Mana Lens that grants resistance to nearby entities or blocks, reducing damage taken from mana-based sources.', 'Mana Lens + Resistance + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(35, 'Tripwire Tripwire', 'Mana Manipulation', 'A Mana Lens that triggers when mana interacts with a tripwire-like mechanism.', 'Mana Lens + Tripwire + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(36, 'Velocity Velocity', 'Mana Manipulation', 'A Mana Lens that causes mana to move at a high velocity, increasing the speed of its transfer.', 'Mana Lens + Velocity + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(37, 'Warp Warp', 'Mana Manipulation', 'A Mana Lens that warps space and time, distorting mana flows and creating unpredictable results.', 'Mana Lens + Warp + Livingwood', 1);
INSERT INTO botania.functionalblocks(BlockID, Name, AutomationType, Description, CraftingRecipe, UsesMana) VALUES
(38, 'Weight Weight', 'Mana Manipulation', 'A Mana Lens that adds weight to nearby blocks or entities, causing them to become heavier and harder to move.', 'Mana Lens + Weight + Livingwood', 1);