--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.225.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2025.06.02 10:49:11
-- Server version: 10.4.32
--

SET NAMES 'utf8';

INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(1, 'Red', 'Mystical Red Flower + Mana', 'Used in crafting Mana-Gathering Flowers, Functional Flowers, Utility Flowers', 0);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(2, 'Blue', 'Mystical Blue Flower + Mana', 'Used in crafting Mana-Gathering Flowers, Functional Flowers, Utility Flowers', 0);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(3, 'Yellow', 'Mystical Yellow Flower + Mana', 'Used in crafting Mana-Gathering Flowers, Functional Flowers, Utility Flowers', 0);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(4, 'Green', 'Mystical Green Flower + Mana', 'Used in crafting Mana-Gathering Flowers, Functional Flowers, Utility Flowers', 0);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(5, 'White', 'Mystical White Flower + Mana', 'Used in crafting Mana-Gathering Flowers, Functional Flowers, Utility Flowers', 0);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(6, 'Purple', 'Mystical Purple Flower + Mana', 'Used in crafting Mana-Gathering Flowers, Functional Flowers, Utility Flowers', 0);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(7, 'Black', 'Mystical Black Flower + Mana', 'Used in crafting Mana-Gathering Flowers, Functional Flowers, Utility Flowers', 1);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(8, 'Pink', 'Mystical Pink Flower + Mana', 'Used in crafting Mana-Gathering Flowers, Functional Flowers, Utility Flowers', 1);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(9, 'Orange', 'Mystical Orange Flower + Mana', 'Used in crafting Mana-Gathering Flowers, Functional Flowers, Utility Flowers', 0);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(10, 'Lime', 'Mystical Lime Flower + Mana', 'Used in crafting Mana-Gathering Flowers, Functional Flowers, Utility Flowers', 0);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(11, 'Brown', 'Mystical Brown Flower + Mana', 'Used in crafting Mana-Gathering Flowers, Functional Flowers, Utility Flowers', 0);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(12, 'Violet', 'Mystical Violet Flower + Mana', 'Used in crafting Mana-Gathering Flowers, Functional Flowers, Utility Flowers', 0);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(13, 'Light Blue', 'Mystical Light Blue Flower + Mana', 'Used in crafting Mana-Gathering Flowers, Functional Flowers, Utility Flowers', 0);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(14, 'Magenta', 'Mystical Magenta Flower + Mana', 'Used in crafting Mana-Gathering Flowers, Functional Flowers, Utility Flowers', 0);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(15, 'End', 'Ender Flower + Mana', 'Used in crafting Ender-related flowers like Ender Lily', 1);
INSERT INTO botania.petals(PetalID, Color, CraftingRecipe, UsedInCrafting, Rarity) VALUES
(16, 'Nether', 'Nether Flower + Mana', 'Used in crafting Nether-related flowers', 1);