--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.225.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2025.06.02 10:49:16
-- Server version: 10.4.32
--

SET NAMES 'utf8';

INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(1, 'Red', 'Mystical Red Flower + Mana', 'Used to grow Mystical Red Flowers', 0);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(2, 'Blue', 'Mystical Blue Flower + Mana', 'Used to grow Mystical Blue Flowers', 0);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(3, 'Yellow', 'Mystical Yellow Flower + Mana', 'Used to grow Mystical Yellow Flowers', 0);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(4, 'Green', 'Mystical Green Flower + Mana', 'Used to grow Mystical Green Flowers', 0);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(5, 'White', 'Mystical White Flower + Mana', 'Used to grow Mystical White Flowers', 0);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(6, 'Purple', 'Mystical Purple Flower + Mana', 'Used to grow Mystical Purple Flowers', 0);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(7, 'Black', 'Mystical Black Flower + Mana', 'Used to grow Mystical Black Flowers', 1);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(8, 'Pink', 'Mystical Pink Flower + Mana', 'Used to grow Mystical Pink Flowers', 1);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(9, 'Orange', 'Mystical Orange Flower + Mana', 'Used to grow Mystical Orange Flowers', 0);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(10, 'Lime', 'Mystical Lime Flower + Mana', 'Used to grow Mystical Lime Flowers', 0);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(11, 'Brown', 'Mystical Brown Flower + Mana', 'Used to grow Mystical Brown Flowers', 0);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(12, 'Violet', 'Mystical Violet Flower + Mana', 'Used to grow Mystical Violet Flowers', 0);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(13, 'Light Blue', 'Mystical Light Blue Flower + Mana', 'Used to grow Mystical Light Blue Flowers', 0);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(14, 'Magenta', 'Mystical Magenta Flower + Mana', 'Used to grow Mystical Magenta Flowers', 0);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(15, 'End', 'Ender Flower + Mana', 'Used to grow Ender-related flowers like Ender Lily', 1);
INSERT INTO botania.seeds(SeedID, Color, CraftingRecipe, UsedFor, Rarity) VALUES
(16, 'Nether', 'Nether Flower + Mana', 'Used to grow Nether-related flowers', 1);